// <auto-generated />
namespace warehouse_asp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class catalogs_products_20170319_1249 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(catalogs_products_20170319_1249));
        
        string IMigrationMetadata.Id
        {
            get { return "201703191049372_catalogs_products_20170319_1249"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
